create table if not exists test(
   id INTEGER primary key,
   name VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS OVERVIEW_ROA_RATIO(
  ASN INTEGER PRIMARY KEY,
  TOTAL INTEGER,
  FILTER INTEGER,
  REMOVE INTEGER,
  AS_RANK INTEGER,
  ORGANIZATION VARCHAR(256),
  COUNTRY  VARCHAR(256),
  COUNTRY_ISO VARCHAR(256),
  RATIO FLOAT
);

CREATE TABLE IF NOT EXISTS AS_SPECIFIC_ROA_RATIO(
    ASN INTEGER PRIMARY KEY,
    RECORD_DATE DATE,
    TOTAL INTEGER,
    FILTER INTEGER,
    REMOVE INTEGER,
    RATIO FLOAT
);

CREATE TABLE IF NOT EXISTS INFERENCE_RESULTS(
    ASN INTEGER PRIMARY KEY,
    TARGET_ASN INTEGER,
    FILTER FLOAT,
    RECORD_DATE DATE,
    PREFIX VARCHAR(256)
);